### ISSUE TITLE
Bug: Automatic models folder deletion after re-installation

### ISSUE THREAD

**Issue by dbouget** [raidionics/Raidionics#40]
On Ubuntu and Mac, the .raidionics is not deleted during the installation process.

An automatic deletion of the Models folder should be performed, based on the software version, to prevent issues due to old models still existing on disk but likely not forward-compatible.

**Comment by andreped** [comment]
@dbouget I thought you added a fix for this when the program is launched the first time after installation?

**Comment by dbouget** [comment]
We can leave the automatic removal of the models folder upon installation for Windows only.

In general, there is an option in the Settings panel to manually request a purge of the models folder (by clicking the trash bin icon).
