### ISSUE TITLE
GUI-Tumor sub-compartments

### ISSUE THREAD

**Issue by gusSCIMOV** [raidionics/Raidionics#59]
**Amazing tool: Just a question: I[m using four MRI modalities for GBM cases. Can you help me out to figure out how I can set up the model to get tumor sub-compartments (necrotic core, enhancing tumor and edema)?**

Thanks
Gustavo

**Comment by andreped** [comment]
Hello, @gusSCIMOV! We have yet to add support for such a model, but we recently participated in BraTS, so we might add such a model in the near future. Shall we integrate the model we made for BraTS?

What do you think, @dbouget?

**Comment by andreped** [comment]
I think @dbouget added support for a model trained on BraTS in 65cad4b18272db62ac475812c0361bea83ee8a53.

A release including this model will be made available shortly, @gusSCIMOV!

**Comment by dbouget** [comment]
Hi @gusSCIMOV,
A new [release](https://github.com/raidionics/Raidionics/releases/tag/v1.2.2) is available, with the option to perform multiclass segmentation and retrieve the tumor sub-compartments.

For now, only our in-house trained models over the BraTS datasets are available, so you should expect worse performances than with the best BraTS models, or than with our single-class models. I will look into the possibility to make available other BraTS models in the future.

For enabling the multiclass segmentation, you simply need to modify the _Output classes_ option in _Settings > Preferences > Processing - Segmentation > Segmentation models_.
