### ISSUE TITLE
Preparing the configuration file for running MRI_GBM_Postop_FV_5p model in Colab Notebook

### ISSUE THREAD

**Issue by gusSCIMOV** [raidionics/Raidionics#67]
Hi Could you please get me a quick guidance to update the [https://colab.research.google.com/gist/dbouget/f87576cdae559ce2a328f0ba7f60828d/02_run_simple_reporting.ipynb](url) notebook ? as I'm interested in running the post-op model ( MRI_GBM_Postop_FV_5p) and I'd like to know how to set up rightly the respective pipeline.json file in. I've already tried the GUI releases, but I'd like to setup it accordingly for running in another server with better capabilities. 
So far, I'm grateful with this great tool.
Best 
GP

**Comment by gusSCIMOV** [comment]
Oh thank you so much for your timely and quick reply. Works pretty good with the Pre-op Post-op pair.
Just  a more specific question about it:
Even though we should include the pre-surgical tumor burden to get better estimation of the post-surgery, I'm dealing with a mix of MRI collection where Pre-operative scans are not always available. In those case May I comment and skip the steps involving Pre-op MRI ? For example; going over these full blocks where I can find this

pipeline_json[step_str]["fixed"]["sequence"] = "T1-CE"
pipeline_json[step_str]["description"] = "Registration from T1-CE (T0) to T1-CE (T1)"

pipeline_json[step_str]["inputs"]["3"]["timestamp"] = 0
pipeline_json[step_str]["inputs"]["3"]["sequence"] = "T1-CE"
pipeline_json[step_str]["inputs"]["3"]["labels"] = None
pipeline_json[step_str]["inputs"]["3"]["space"] = {}
pipeline_json[step_str]["inputs"]["3"]["space"]["timestamp"] = 1
pipeline_json[step_str]["inputs"]["3"]["space"]["sequence"] = "T1-CE"

Thanks 
GP

**Comment by dbouget** [comment]
I've updated the [README](https://github.com/raidionics/Raidionics-models) to the Raidionics model zoo. There are 5 different postop glioblastoma segmentation models, each trained for a specific set of inputs.

If you need to run a model on postop MR scans only, you can look at the following models: MRI_GBM_Postop_FV_1p, MRI_GBM_Postop_FV_2p, and MRI_GBM_Postop_FV_3p. There is a **pipeline.json** file inside each model folder, where you can copy the actual pipeline required for running the segmentation with the specific model.

**Comment by gusSCIMOV** [comment]
Hi 
I've been working a time ago with many of the Colab notebooks added in "processing backend for performing segmentation and computation of standardized report (RADS)" coming up from this request by the way.  It has been quite useful 

I just wondering if I might get the BRATs-like output (Edema, enhancing, necrosis) using just the post-operative scans using the MRI_GBM_Postop_FV_1p or FV_3p, instead of the whole tumor mask, does it make sense now?

Thanks, a really appreciate your help

**Comment by andreped** [comment]
@gusSCIMOV AFAIK, there has not been trained such a model for postoperative scans (yet). But I know @dbouget is working on expanding the model to include more classes in the postoperative case. However, I am not sure what the status is on that. Likely still a WIP.

I believe @dbouget is on holiday till Tuesday. He will likely not reply until then at the earliest.

---
NOTE: Next time I recommend making a separate issue and referring to this old issue (if relevant) instead of extending this thread. Making a new issue for this, makes it easier for us to track "unsolved" issues and for others to potentially find solutions to their own problems. I hope you understand :]

**Comment by gusSCIMOV** [comment]
Sure, it would be great if there is some progress in that expanded model
